name: Github sactions - Pull request
run-name: Running - ${{ github.event_name }}
on: [pull_request]

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário Pull request - Pull"