name: Github sactions - Pull Request Types
run-name: Running - ${{ github.event_name }}
on: 
  # Apenas mostrando que é possível mistruar os de pull request aos de push como por exemplo o "pull_request" e estando na branch main
  pull_request:
    types: 
      # Qualquer tipo de pull request
      - opened
      - reopened
      - closed
    branches:
      - main 
    paths: 
      - '**.txt'      

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário Pull request - Types"