name: GitHub Actions - Configuração de Variavel de Ambiente
run-name: Running - ENV Var Repo Config
on: [push, workflow_dispatch]

# Criando variaveis na própria pipeline e trazendo variaveis do github para a pipeline
env: 
  variavel: "Bom dia"
  var_1: ${{ vars.VAR_TEST}}
  var_2: ${{ secrets.test_secret}}

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "$variavel"
          echo "$var_1"
          echo "$var_2"

