name: Github sactions - Workflow dispatch
run-name: Running - ${{ github.event_name }}
on: [workflow_dispatch]

# Ativado somente quando for executado manualmente
jobs: 
  on-workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário Workflow dispatch"