
name: Github sactions - Push Template Branches
run-name: Running - ${{ github.event_name }}
on: 
  push: 
    branches: 
      - main
      - develop
      # Dessa forma todas as branches que seguirem esse padrão serão acionadas
      - 'release/**'

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário Branch workflow - branches ON"