name: Github sactions - Push Template Path
run-name: Running - ${{ github.event_name }}
on: 
  push: 
    paths: 
      # Realiza o push somente quando algum arquivo .txt seja alterado
      - '**.txt'

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário Paths Workflow - Paths teste"