name: GitHub Actions - Teste com dependência Template
run-name: Running - Teste com dependência Template
on: [push, workflow_dispatch]

jobs:
  test_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Execução Setup"

  test_api:
    # Desta forma só chegará aqui se o passo anterior funcionar, se não funcionar tudo será cortado e finalizado
    needs: test_unit
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Execução test"
  
  test_ui:
    needs: [test_unit, test_api]
    # needs: test_api
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Execução test"