name: Github sactions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on: 
  pull_request:
    branches:
      # Será ativado quando houve algum PR para a branch selecionada
      - main

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário Paths Workflow - Paths teste"