name: GitHub Actions - Matrix strategy Template
run-name: Running - Matrix
on: [push, workflow_dispatch]

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        # Dessa forma rodamos esses 3 jobs em paralelo
        navegador: [chrome, firefox, webkit]
        # Supondo que sejam 3 tipos diferentes como test de create, update e delete
        # Todas as tags seram executada em cada um dos três parâmetros de navegador
        tag: [tag_1, tag_2, tag_3]
      # Se falhar algum teste ele para a execução da matrix, por default como true
      fail-fast: false
    steps:
      - name: Comentário
        run: |
          echo ${{ matrix.navegador }}
          echo ${{ matrix.tag }}
          