
name: Github sactions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on: 
  push: 
    branches-ignore: 
      - main
      # Dessa forma podemos ignorar especificamente alguma branch

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário PUSH WORKFLOW - Branch Ignore"